version: '3'
services:
  nezukoBot:
    image: callmekory/nezuko
    container_name: nezuko
    volumes:
      - ./nezukoDocker/config:/app/build/config
      - ./nezukoDocker/logs:/app/logs
    ports:
      - 5700:5700
    network_mode: bridge
    restart: unless-stopped
